# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{.Release.Name}}-configmap
# data:
#   myvalue: "Hello World!"
#   #drink: {{.Values.favorite.drink | default "tea" | quote}}
#   {{- with .Values.favorite }}
#   #drink: {{.Values.favorite.drink | default "tea" | quote}}
#   drink: {{.drink | default "tea" | quote}}
#   dessert: {{.Values.favorite.dessert | quote}}
#   food: {{ .food | upper | quote }} #{{.Values.favorite.food | upper | quote}}
#         # **{{- if eq .Values.favorite.drink "coffee"}}
#         # mug: "true"*
#         # **{{- end }}
#         {{- end }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-configmap
# data:
#   myvalue: "Hello World"
#   {{- with .Values.favorite }}
#   drink: {{ .drink | default "tea" | quote }}
#   dessert: {{ .dessert | quote }}
#   food: {{ .food | upper | quote }}
#   {{- end }}
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-configmap
# data:
#   myvalue: "Hello World"
#   {{- with .Values.favorite }}
#   drink: {{ .drink | default "tea" | quote }}
#   food: {{ .food | upper | quote }}
#   {{- end }}
#   toppings: |-
#     {{- range .Values.pizzaToppings }}
#     - {{ . | title | quote }}
#     {{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{- template "mychart.labels" }}
data:
  myvalue: "Hello World"
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}